### ISSUE TITLE
Add individual colours to denote pass/fail

### ISSUE THREAD

**Issue by haldaried** [liamsain/test-case-tracker#1]
Can you please remove the generic pass/fail slider.

Please replace with an individual slider next to each device. Three options. Green, Red or N/a. This so we can pass, fail or exclude each device against each test case.

**Comment by liamsain** [comment]
sure!

**Comment by haldaried** [comment]
Hey Buddy!
Hope you are well and enjoying your new job. We all miss you!
Have you had a chance to look at the above amendments to your wonderful program :)

**Comment by liamsain** [comment]
hey Andrew. doing good thanks. I miss you all too!

Just updated it, let me know if you find bugs

Liam

**Comment by haldaried** [comment]
Will do mate, take care and thank you :)

**Comment by liamsain** [comment]
Just noticed a couple of really bad bugs. I’ll fix tonight

Liam

On 18 Jun 2019, at 09:56, haldaried <notifications@github.com<mailto:notifications@github.com>> wrote:


Will do mate, take care and thank you :)

**Comment by haldaried** [comment]
No worries mate 🙂
________________________________

**Comment by liamsain** [comment]
ok, that should be fixed. Let me know if you find anything else

**Comment by haldaried** [comment]
Hey mate

Thanks will do ☺
